### ISSUE TITLE
Generic programming

### ISSUE THREAD

**Issue by d0niek** [php-ds/extension#76] opened 2017-03-06 10:43 UTC
Are there any plans to make Vector/Map/Set/etc generic?
```php
public function find(Vector<int> $ids): Object {}
```
```php
Map<string, int>
```

**Comment by rtheunissen** [comment] 2017-03-07 00:22
Only when PHP supports this natively.

**Comment by teohhanhui** [comment] 2017-03-08 07:48
Duplicate of #73

**Closed** 2017-03-08 09:06 UTC
Labels: Duplicate, No-op
