### ISSUE TITLE
unable to install with cygwin

### ISSUE THREAD

**Issue by legale** [php-ds/extension#118] opened 2018-07-28 09:33 UTC
Hello. I'm trying to install your extension on windows10 machine with cygwin `pecl install ds`
The compilation process is interrupted with the following error:
```
linker --out-implib -Xlinker .libs/ds.dll.a
src/php/classes/.libs/php_collection_ce.o:php_collection_ce.c:(.rdata$.refptr.php_json_serializable_ce[.refptr.php_json_serializable_ce]+0x0): undefined refere
nce to `php_json_serializable_ce'
collect2: error: ld returned 1 exit status
make: *** [Makefile:289: ds.la] Ошибка 1
ERROR: `make' failed
```
PHP version:
```
PHP 7.1.16 (cli) (built: Apr 10 2018 18:09:30) ( NTS )
```

**Comment by rtheunissen** [comment] 2018-07-28 10:58
`ds` depends on the `json` extension which needs to be loaded first. Might be related to https://github.com/php-ds/extension/issues/2 ?

**Comment by rtheunissen** [comment] 2018-08-02 16:13
I think this is a duplicate of #2

**Closed by rtheunissen** 2018-08-02 16:13 UTC
Labels: PECL, Windows
